In [1]:
import numpy as np

In [4]:
arr = np.load('data/E116/saved_runs/regression/model_2021-06-26-at-06-10-03_train_metrics.npy', allow_pickle=True)

In [9]:
for a in arr:
    print(a.shape)

(11689,)
(11689,)
(11689,)
(2000,)
(2000, 1)


In [10]:
arr

array([array([ 60577,  22060, 223671, ...,  79211,  81896,  63504]),
       array([1.1804807 , 0.08483355, 0.07370858, ..., 0.09427215, 0.06354579,
              0.07009982], dtype=float32)                                     ,
       array([1.0009111 , 0.        , 0.        , ..., 0.00216606, 0.        ,
              0.        ], dtype=float32)                                     ,
       array([-0.02127084, -0.0063161 ,  0.01739647, ...,  0.82042446,
               0.82097269,  0.82149857])                              ,
       array([[0.71825153],
              [0.71065712],
              [0.70308411],
              ...,
              [0.13559677],
              [0.1352322 ],
              [0.13487883]])], dtype=object)